mock_profiles = [
  {
    "name": "Mauro Brero",
    "age": 28,
    "location": "Palermo, CABA",
    "bio": "Fanático del fútbol y jugador de Boca Juniors amateur. Busco compañeros para jugar los fines de semana en las canchas de Palermo. También me gusta correr por los bosques.",
    "sports": ["Fútbol", "Running", "Tenis"],
    "distance": 2.5,
    "profilePicture": "/images/profile1.png",
  },
  {
    "name": "Damian Dalla Vía",
    "age": 26,
    "location": "Belgrano, CABA",
    "bio": "Estudiante de educación física. Me gusta entrenar en el gimnasio y jugar al tenis. Busco compañeros para actividades al aire libre y para mejorar mi técnica en tenis.",
    "sports": ["Tenis", "Gimnasio", "Natación"],
    "distance": 3.8,
    "profilePicture": "/images/profile2.png",
  },
  {
    "name": "Elias Ojeda",
    "age": 25,
    "location": "Recoleta, CABA",
    "bio": "Apasionado del básquet y el running. Entreno 4 veces por semana y busco compañeros para motivarnos mutuamente. Me encanta la competencia sana y superarme día a día.",
    "sports": ["Básquet", "Running", "Ciclismo"],
    "distance": 1.7,
    "profilePicture": "/images/profile3.png",
  },
  {
    "name": "Tomas Brusco",
    "age": 22,
    "location": "Núñez, CABA",
    "bio": "Entrenador personal y amante del fitness. Busco compañeros para entrenar en el gimnasio o hacer actividades al aire libre. Puedo ofrecer consejos sobre nutrición y entrenamiento.",
    "sports": ["Gimnasio", "Crossfit", "Funcional"],
    "distance": 4.2,
    "profilePicture": "/images/profile4.png",
  },
  {
    "name": "Santiago López",
    "age": 28,
    "location": "Caballito, CABA",
    "bio": "Jugador de pádel nivel intermedio. También disfruto del ciclismo los fines de semana por los bosques de Palermo. Busco gente con buena onda para compartir deportes y quizás un mate después.",
    "sports": ["Pádel", "Ciclismo", "Natación"],
    "distance": 5.1,
    "profilePicture": "/images/profile5.jpeg",
  },
  {
    "name": "Martín Acosta",
    "age": 29,
    "location": "Villa Urquiza, CABA",
    "bio": "Jugador de básquet de toda la vida. Busco equipo para jugar los domingos por la mañana o compañeros para entrenar. Nivel intermedio-avanzado, pero abierto a jugar con todos.",
    "sports": ["Básquet", "Fútbol", "Running"],
    "distance": 6.3,
    "profilePicture": "/images/profile3.png",
  },
  {
    "name": "Lucas Giménez",
    "age": 24,
    "location": "Villa Crespo, CABA",
    "bio": "Apasionado del fútbol desde chico. Juego como mediocampista y busco un equipo para partidos semanales. También me gusta el entrenamiento funcional y correr por las mañanas.",
    "sports": ["Fútbol", "Funcional", "Running"],
    "distance": 3.2,
    "profilePicture": "/images/profile1.png",
  },
]
